import { chromium } from 'playwright';
import { mkdir, writeFile } from 'node:fs/promises';
const origin = process.env.REDRAIN_TEST_ORIGIN || 'http://127.0.0.1:4189';
const output = 'output/redrain-package-qa';
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ headless: true, channel: 'chrome' });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
const page = await context.newPage();
const errors = [];
page.on('pageerror', error => errors.push(error.message));
page.on('response', response => { if (response.status() >= 400) errors.push(`${response.status()} ${response.url()}`); });
const assert = (condition, message) => { if (!condition) throw new Error(message); };
await page.goto(`${origin}/games/redrain/index.html`);
await page.waitForFunction(() => typeof window.render_game_to_text === 'function');
await page.locator('#prologue-image').evaluate(image => image.decode());
const button = await page.locator('#prologue-next').boundingBox();
assert(button.y + button.height <= 1000, 'Desktop prologue button is cut off');
await page.screenshot({ path: `${output}/standalone-desktop.png` });
await page.setViewportSize({ width: 390, height: 844 });
const mobileButton = await page.locator('#prologue-next').boundingBox();
await page.screenshot({ path: `${output}/standalone-mobile.png` });
assert(mobileButton.y + mobileButton.height <= 844 && mobileButton.x + mobileButton.width <= 390, `Mobile prologue button is cut off: ${JSON.stringify(mobileButton)}`);
await page.setViewportSize({ width: 1440, height: 1000 });
await page.goto(`${origin}/`);
await page.evaluate(async () => {
  const { createSnapshot, freshPlatformState } = await import('/games/redrain/src/platform-state.js');
  window.latestSave = createSnapshot({ ...freshPlatformState(), mode: 'game', tutorialSeen: true, prologueIndex: 4 }, []);
  window.messages = [];
  window.legacyAccess = [];
  window.session = crypto.randomUUID();
  window.sendChild = (type, payload = {}) => document.querySelector('iframe').contentWindow.postMessage({ channel: 'redleaf:redrain:v1', sessionId: window.session, type, ...payload }, location.origin);
  window.addEventListener('message', event => {
    const message = event.data;
    if (event.source !== document.querySelector('iframe')?.contentWindow || message?.channel !== 'redleaf:redrain:v1' || message.sessionId !== window.session) return;
    window.messages.push(message);
    if (message.type === 'ready') window.sendChild('restore', { save: window.latestSave, settings: { textSize: 20, textSpeed: 100, sound: false, reducedMotion: true } });
    if (message.type === 'checkpoint') {
      window.latestSave = message.save;
      window.sendChild('saved', { requestId: message.requestId, ok: true });
    }
  });
  document.body.innerHTML = '<iframe title="test" style="border:0;width:100vw;height:100vh;position:fixed;inset:0"></iframe>';
  document.querySelector('iframe').src = `/games/redrain/index.html?embedded=1&session=${window.session}`;
});
await page.waitForFunction(() => window.messages.some(message => message.type === 'restored'));
const frame = page.frameLocator('iframe');
for (let i = 0; i < 30 && !(await frame.locator('#choice-list').isVisible()); i++) await frame.locator('#reading-advance').click();
await frame.locator('.choice-btn').first().click();
await page.waitForFunction(() => window.latestSave.state.route.length === 1);
await page.screenshot({ path: `${output}/embedded-choice.png` });
const chosen = await page.evaluate(() => JSON.parse(JSON.stringify(window.latestSave)));
await page.evaluate(() => window.sendChild('settings', { settings: { textSize: 21, textSpeed: 100, sound: false, reducedMotion: true }, paused: true }));
await page.waitForFunction(() => JSON.parse(document.querySelector('iframe').contentWindow.render_game_to_text()).platform.paused === true);
await page.evaluate(() => window.sendChild('settings', { settings: { textSize: 21, textSpeed: 100, sound: false, reducedMotion: true }, paused: false }));
await page.evaluate(() => window.sendChild('command', { command: 'exit' }));
await page.waitForFunction(() => window.messages.some(message => message.type === 'exit'));
await page.evaluate(() => { window.messages = []; document.querySelector('iframe').contentWindow.location.reload(); });
await page.waitForFunction(() => window.messages.some(message => message.type === 'restored'));
const restored = await page.evaluate(() => window.latestSave);
assert(JSON.stringify(chosen.state.route) === JSON.stringify(restored.state.route), 'Route was not restored');
assert(chosen.state.sceneIndex === restored.state.sceneIndex && chosen.state.outcome === restored.state.outcome, 'Scene/outcome was not restored');
assert(errors.length === 0, `Browser errors: ${errors.join(', ')}`);
const messages = await page.evaluate(() => window.messages.map(message => message.type));
await writeFile(`${output}/report.json`, JSON.stringify({ origin, desktopButton: button, mobileButton, savedRoute: chosen.state.route, restoredRoute: restored.state.route, restoredReadingCursor: restored.state.readingCursor, messages, errors }, null, 2));
await browser.close();
console.log(JSON.stringify({ ok: true, output, savedRoute: chosen.state.route, errors }));
