import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { chromium, type Page } from 'playwright';
import { storageKeys, defaultSettings } from '../src/game.ts';
import { originalStoryLinks } from '../shared/original-links.ts';

const base = 'http://127.0.0.1:4173';
const output = resolve('output/playwright/original-links-20260910');
await mkdir(output, { recursive: true });
const library = await (await fetch(`${base}/api/stories`)).json();
const projects = await (await fetch(`${base}/api/workshop/projects`)).json();
const results: unknown[] = [];
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const state = (page: Page) => page.evaluate(() => JSON.parse(window.render_game_to_text!()));
const progress = (value: any) => ({ node: value.nodeId, resources: value.resources, choices: value.choiceCount, difficulty: value.difficulty, rewinds: value.rewindsRemaining });
try {
  for (const viewport of [{ width: 1440, height: 1000 }, { width: 390, height: 844 }]) {
    const context = await browser.newContext({ viewport });
    await context.addInitScript(({ keys, settings }) => {
      localStorage.setItem(keys.onboarding, 'true');
      localStorage.setItem(keys.settings, JSON.stringify(settings));
    }, { keys: storageKeys, settings: { ...defaultSettings, reducedMotion: true, textSpeed: 100 } });
    const page = await context.newPage();
    const errors: string[] = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(base, { waitUntil: 'domcontentloaded' });
    const blue = page.locator('.story-card').filter({ has: page.getByRole('heading', { name: '蓝血', exact: true }) });
    await blue.getByRole('button', { name: '读原作', exact: true }).click({ timeout: 45000 });
    const reader = page.getByRole('dialog', { name: '原作节选', exact: true });
    const link = reader.getByRole('link', { name: '前往知乎阅读全文', exact: true });
    assert.equal(await link.getAttribute('href'), originalStoryLinks['2025684191967294692']);
    assert.equal(await link.getAttribute('target'), '_blank');
    assert.ok((await link.getAttribute('rel'))?.includes('noopener'));
    await reader.locator('.source-reader-prose').waitFor({ timeout: 40000 });
    const original = await (await fetch(`${base}/api/stories/2025684191967294692`)).json();
    assert.equal((await reader.locator('.source-reader-prose').innerText()).replace(/\s/g, ''), original.content.replace(/\s/g, ''));
    await link.scrollIntoViewIfNeeded();
    await page.screenshot({ path: resolve(output, `reader-${viewport.width}.png`) });
    const popupPromise = page.waitForEvent('popup');
    await link.click();
    const popup = await popupPromise;
    await popup.waitForURL(originalStoryLinks['2025684191967294692'], { timeout: 30000, waitUntil: 'commit' });
    const navigatedUrl = popup.url();
    await popup.close();
    assert.equal(page.url(), `${base}/`);
    await reader.getByRole('button', { name: '返回故事档案', exact: true }).click();
    const detail = page.getByRole('dialog', { name: '故事档案', exact: true });
    assert.equal(await detail.getByRole('link', { name: '前往知乎阅读全文' }).getAttribute('href'), originalStoryLinks['2025684191967294692']);
    await detail.getByRole('button', { name: '进入故事世界', exact: true }).click();
    await page.getByRole('dialog', { name: '世界序章', exact: true }).getByRole('button', { name: '开始故事', exact: true }).click();
    const before = progress(await state(page));
    await page.locator('.source-reader-link').click();
    await reader.waitFor();
    assert.equal(await link.getAttribute('href'), originalStoryLinks['2025684191967294692']);
    await reader.getByRole('button', { name: '继续当前故事', exact: true }).click();
    assert.deepEqual(progress(await state(page)), before);
    await page.getByRole('button', { name: '返回书库', exact: true }).click();
    const missing = library.stories.find((story: any) => !originalStoryLinks[story.id]);
    assert.ok(missing);
    await page.locator('.story-card').filter({ has: page.getByRole('heading', { name: missing.title, exact: true }) }).getByRole('button', { name: '读原作', exact: true }).click();
    assert.equal(await reader.getByRole('link', { name: '前往知乎阅读全文', exact: true }).count(), 0);
    const searchUrl = new URL((await reader.getByRole('link', { name: '在知乎查找原作', exact: true }).getAttribute('href'))!);
    assert.ok(searchUrl.searchParams.get('q')?.includes(missing.title));
    assert.ok((await reader.innerText()).includes('暂未核实原作直达链接'));
    await page.screenshot({ path: resolve(output, `unverified-${viewport.width}.png`) });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
    await reader.getByRole('button', { name: '关闭', exact: true }).click();
    await page.getByRole('button', { name: '新故事工作台', exact: true }).click();
    const imported = projects.projects.find((project: any) => project.playable && project.origin?.kind === 'zhihu-article');
    assert.ok(imported);
    const projectButton = page.getByRole('button').filter({ hasText: imported.title }).first();
    await projectButton.click();
    const readButton = page.getByRole('button', { name: '阅读原文', exact: true });
    if (await readButton.count()) await readButton.click();
    else await page.getByRole('button', { name: /原文/ }).last().click();
    const importedReader = page.locator('.imported-reader');
    await importedReader.waitFor();
    assert.equal(await importedReader.getByRole('link', { name: '前往知乎阅读全文', exact: true }).getAttribute('href'), imported.origin.sourceUrl);
    await page.screenshot({ path: resolve(output, `imported-${viewport.width}.png`) });
    assert.deepEqual(errors, []);
    results.push({ viewport, originalNavigation: navigatedUrl, unchangedGameProgress: before, importedOriginal: imported.origin.sourceUrl, missingLink: missing.title, pageErrors: errors });
    await context.close();
  }
} finally {
  await browser.close();
  await writeFile(resolve(output, 'report.json'), JSON.stringify({ base, status: results.length === 2 ? 'passed' : 'incomplete', results }, null, 2));
}
console.log(JSON.stringify({ passed: results.length, output }));
