import type { Choice, SceneNode, ResourceDefinition } from '../shared/types.ts';
import type { AuthoredWorld } from './worlds.ts';
import { expandCatalogB } from './catalog-b-expansions.ts';
import { polishBChoices } from './catalog-b-prose.ts';
import { correctBLiveProse } from './catalog-b-live-prose.ts';
import { withCatalogBEditorial } from './catalog-b-editorial.ts';

const c = (id: string, text: string, nextNodeId: string, effects?: Choice['effects'], requires?: Choice['requires'], feedback?: Choice['feedback']): Choice => ({ id, text, nextNodeId, effects, requires, feedback });
const s = (id: string, title: string, location: string, text: string[], choices: Choice[], challenge?: SceneNode['challenge']): SceneNode => ({ id, chapter: '行旅', title, location, time: '此刻', text, choices, background: '', challenge });
const e = (id: string, title: string, text: string[], tone: 'hopeful' | 'uneasy' | 'dark'): SceneNode => ({ id, title, chapter: '终章', location: '余页', time: '之后', text, choices: [], background: '', ending: { title, text: text[text.length - 1], tone } });
const r = (id: string, label: string, initial: number, max: number, description: string): ResourceDefinition => ({ id, label, initial, min: 0, max, description });
const q = (kind: NonNullable<SceneNode['challenge']>['kind'], prompt: string, hint: string): SceneNode['challenge'] => ({ kind, prompt, hint });
function make(meta: { id: string; storyId: string; title: string; author: string; player: string; role: string; summary: string; objective: string; intro: string[]; note: string; resources: ResourceDefinition[]; mechanics: NonNullable<AuthoredWorld['mechanics']> }, entries: SceneNode[]): AuthoredWorld {
  const art = `/assets/${meta.id}.webp`;
  return { id: meta.id, storyId: meta.storyId, title: meta.title, subtitle: meta.objective, summary: meta.summary, objective: meta.objective, introduction: meta.intro, player: { name: meta.player, role: meta.role }, startNodeId: entries[0].id, characters: [], version: '1.0.0', cover: art, background: art, resources: meta.resources, mechanics: meta.mechanics, source: { title: meta.title, author: meta.author, url: `https://api.zhihu.com/km-indep-home/hackathon/v2/story/${meta.storyId}` }, adaptation: { scope: 'based-on-api-excerpt', adultCast: true, note: `基于知乎接口真实节选。行动分支、数值和结局为游戏原创，不代表原作后续。所有登场角色均为成年人。${meta.note}` }, nodes: Object.fromEntries(entries.map(node => [node.id, { ...node, background: art }])) };
}

const templeHeart = make({ id: 'temple-heart', storyId: '2025954672918163637', title: '吃人心的小妖怪', author: '女巫', player: '山中妖灵', role: '第一次答应救人的成年妖灵', summary: '一颗吃不到的心，一项撑不住的约定。有限的灵力，该用来维持承诺，还是查清病人为何停在康复门前？', objective: '查明恢复停滞的原因，决定救人与成仙的代价。', intro: ['你活了几百年，一直相信吃满一万颗人心就能成仙，却连第一颗也没吃到。', '土庙外，毓娘请求你救念念。你终于答应，才发现自己的灵力远比说出口的承诺少。', '本局把念念设为二十二岁的女儿。你面对的仍是那位愿意拿自己换她的母亲。'], note: '原文念念为七岁；本局明确改为二十二岁。诊疗均为幻想叙事，游戏没有补写原作未提供的成仙真相。', resources: [r('spirit', '灵力', 4, 6, '施法与查验消耗，回山休养恢复。'), r('days', '余日', 5, 6, '往返与休养占用约定期限。')], mechanics: { title: '施法与休养', description: '持续灌注可能耗尽灵力；问诊、食物与恢复记录支持不同判断。', beginnerTip: '首轮留一点灵力用于查验，比较饮食与恢复记录后再决定是否加大灌注。' } }, [
  s('temple', '神像没有回答', '山顶土庙', ['毓娘把念念抱到火边。你说可以等，却发现自己看着的已经不是一顿饭。', '她把手按在自己胸口，答应以自己的心作偿。你必须先决定能承担多少。'], [c('warm', '添火并少量渡气', 'breath', { resources: { spirit: -1 }, clues: ['渡气后呼吸恢复'] }), c('ask', '先问她一路如何上山', 'promise', { clues: ['长途搬运'], trust: 3 })]),
  s('breath', '胸口动了一下', '庙外火堆', ['念念的呼吸暂时恢复，眼睛没有睁开。毓娘问你为什么不能再多给一点。', '你能承认力量有限，也能继续让她相信自己无所不能。'], [c('honest', '说明要分次恢复', 'promise', { clues: ['分次灌注'], trust: 5 }), c('pretend', '许诺下次就能醒来', 'promise', { resolve: -3 })]),
  s('promise', '下山之前', '石阶', ['毓娘背起女儿，肩膀沉下去。你又喊住她，说下次由你下山。', '她点头。火还烧着，你已经开始计算灵力。'], [c('escort', '陪她走过最陡的一段', 'rest', { resources: { spirit: -1 }, clues: ['长途搬运'], trust: 4 }), c('ration', '留下清粥的嘱咐和下次日期', 'rest', { clues: ['清粥饮食'] })]),
  s('rest', '神像前的空位', '土庙', ['你拿起供品，照例向神像道谢。神像的笑与昨天毫无区别。', '恢复力量需要时间。再急，也不能从空空的掌心变出灵气。'], [c('recover', '休养一日再出发', 'visit', { resources: { spirit: 3, days: -1 } }), c('hurry', '趁天未黑立即下山', 'visit', { resources: { days: 1 } })], q('resource', '保住期限，还是补回灵力？', '后面查验需要灵力；余日耗尽仍可求援，但无法完成自己的连续观察。')),
  s('visit', '竹床边的米碗', '毓娘家', ['毓娘说家里给念念煮的只有稀粥。床上的念念比初见时有了血色，却仍坐不稳。', '眼前的气色不能说明她每天实际吃下多少，你还没有这份记录。'], [c('bowl', '核对米碗与每天剩下的量', 'check', { clues: ['清粥饮食', '每日摄入记录'], resources: { days: -1 } }), c('pulse', '检查灌注后的变化', 'check', { clues: ['渡气后呼吸恢复'], resources: { spirit: -1 } }, undefined, { tone: 'success', text: '你少量渡入灵力，核对呼吸的变化；这次查验没有补上每天的饮食记录。' })]),
  s('check', '醒来不是痊愈', '竹床旁', ['念念轻轻叫了一声母亲。毓娘伸手捂住嘴，又立即问她哪里疼。', '你要把这一步与先前的变化分开记，还是把它当作承诺即将兑现。'], [c('record', '记录呼吸、睁眼和说话的次序', 'meal', { clues: ['恢复阶段记录'] }), c('push', '追加一次渡气', 'meal', { resources: { spirit: -2 }, resolve: -2 })]),
  s('meal', '该吃点好的了', '灶间', ['你提醒毓娘改善饭食。她应得很快，手却在米缸边停了一下。', '这次你没有立刻走。厨房里哪些是见到的事实，哪些只是你以为她做得到的事？'], [c('inspect', '请她说明家中存粮和近日开销', 'woods', { clues: ['米缸见底'], trust: 3 }), c('offer', '将自己的供品分给她们', 'woods', { resources: { days: -1 }, clues: ['补充饭食'], trust: 5 })], q('investigation', '恢复停滞前，哪项条件尚未核实？', '你的嘱咐不等于家里已经有足够食物。')),
  s('woods', '林中的笑声', '山路', ['林中伙伴听说你终于要吃到心，都笑了。它们记得，你连受伤的小兽也会救。', '你气恼地往前走，却想起那些小兽每次恢复后，都得自己找吃的。'], [c('remember', '比较以往救助与这次恢复', 'stalled', { clues: ['恢复需要持续供养'] }), c('recharge', '在林中多留一天积聚灵力', 'stalled', { resources: { spirit: 2, days: -1 } })]),
  s('stalled', '没有再好一点', '毓娘家门口', ['念念能坐起，却仍走不到院子里。毓娘惭愧地低下头，好像病情是她欠你的账。', '你忍住责备，重新想起几次探望。没有亲自核过、留下记录的部分，仍不能算作确定的原因。'], [c('compare', '比较饮食与恢复阶段', 'talk', { clues: ['供养缺口'], resolve: 5 }, { allClues: ['清粥饮食', '恢复阶段记录'] }, { tone: 'success', text: '饮食与恢复阶段可以对应，你发现了需要补足的供养缺口；这仍不能解释所有病情。' }), c('inspect_spirit', '用灵力确认没有新的衰退', 'talk', { clues: ['暂未恶化'], resources: { spirit: -1 } }, undefined, { tone: 'neutral', text: '查验只确认暂未恶化，没有说明恢复为什么停滞。' }), c('overdo', '不再查原因，继续加大灌注', 'collapse', { resources: { spirit: -2 } }), c('pause_check', '承认眼下无法确认，先与母女商议', 'talk', { resolve: -2 }, undefined, { tone: 'neutral', text: '你承认尚未查明原因，准备与母女商议，没有取得新的病情结论。' })], q('deduction', '继续灌注能解决每一种停滞吗？', '恢复记录和实际饮食能支持供养不足的判断；它不是万能诊断。')),
  s('collapse', '掌心的火熄了', '院门', ['你扶住门框，才没有跌下去。毓娘第一次看见你比念念更像需要休息的人。', '继续扮演无所不能的神仙，只会让屋里多一个倒下的人。'], [{ ...c('admit', '承认自己需要休息，接受照料', 'talk', { trust: 5, clues: ['承认力量边界'] }), legacyTexts: ['承认自己耗尽力量，接受照料'] }, c('retreat', '回山休养后再谈', 'talk', { resources: { spirit: 2, days: -1 } })]),
  s('talk', '那颗心不是药钱', '灶台旁', ['毓娘再次说起自己的承诺。你想象过许多次怎样吃那颗心，此刻却只能看见她疲惫的手。', '念念在屋里听着。她有权知道，母亲曾拿什么作抵押。'], [c('release', '解除以心抵偿的约定', 'plan', { clues: ['解除索偿'], trust: 8 }, undefined, { tone: 'success', text: '你明确撤回索偿，毓娘不再欠你那颗心。' }), c('defer', '先把偿还搁下，只讨论眼前照料', 'plan', { resolve: 3 }, undefined, { tone: 'neutral', text: '偿还暂被搁下，原约定尚未正式解除；这次只商议眼前照料。' })]),
  s('plan', '一张新的约定', '小院', ['你们把恢复、吃饭和休养分成三件事。没有谁能凭一次施法承包今后的日子。', '你可以亲自维持余下几次观察，也可以请村中人接续。'], [c('sustain', '补足供养，亲自完成连续观察', 'review', { resources: { days: -1, spirit: -1 }, clues: ['连续照料'] }, { anyClues: ['供养缺口', '米缸见底', '恢复需要持续供养'] }, { tone: 'success', text: '你补上饭食，留下完成这一段观察；病情接下来如何仍要继续看。' }), c('ask_village', '带毓娘向村中求援', 'review', { clues: ['邻里照料'], trust: 4 }, undefined, { tone: 'success', text: '几户人家答应接续送饭，你们约定了轮换；这份援助还不能保证痊愈。' }), c('go', '把能做与不能做的事写清后离开', 'ending_boundary')]),
  s('review', '不再按心计数', '屋檐下', ['午后的饭香飘进院子。照料有了接续，念念能恢复到哪一步仍需观察。', '神像没有开口，母亲留下的话也没有新的解释。你仍要选择怎样活。'], [c('remain', '放下索偿，继续陪她们走完恢复', 'ending_care', undefined, { allClues: ['解除索偿', '连续照料'] }), c('network', '让照料在邻里间接续', 'ending_village', undefined, { allClues: ['邻里照料'] }), c('boundaries', '带走自己的疑问，按约回来探望', 'ending_boundary')]),
  e('ending_care', '心没有被拿走', ['你仍没有成仙，也不知道母亲的话该如何理解。念念却能亲自将饭碗递到你手里。', '这一次你吃的是饭。毓娘不必再把自己的性命当作账单。'], 'hopeful'),
  e('ending_village', '庙外也有人应门', ['几户人家轮流送来饭食，照料不再全压在毓娘与一只妖灵身上。', '神像依旧沉默。山路旁却多了几扇你敲了会有人应的门。'], 'hopeful'),
  e('ending_boundary', '有期限的约定', ['你将下一次探望写在门边，把余下的力量留给活着的人。早先说过多少大话，都不能让这次安排保证痊愈。', '未解的病情与未解的传说都还在那里；今天写下的是照料的期限，不是成仙的保证。'], 'uneasy'),
]);

const tigerShelter = make({ id: 'tiger-shelter', storyId: '1962166083206242442', title: '咪假虎威', author: '反骨', player: '小橘', role: '被误认的成年猫妖', summary: '误入虎穴后，庇护来自一个错误身份。追捕重现时，你要弄清两条鱼的来历，也要决定怎样面对收留自己的人。', objective: '核实追捕缘由，争取不靠假身份维持的庇护。', intro: ['你吃了监天司的两条鱼，被一路追进雨中的山洞。山君君寻秋把你认成了自己的孩子。', '鱼的来历尚不明白，洞外的人却已经追来。留在庇护中与承担责任，并不一定是同一条路。'], note: '原文明确小橘成年；本局君洲、君潮改为成年虎妖，删去幼崽哺育桥段，保留误认亲属与追捕冲突。', resources: [r('stamina', '体力', 4, 6, '跑动与交涉的消耗。'), r('shelter', '庇护', 2, 5, '坦诚与共同应对积累；单独冒险消耗。')], mechanics: { title: '身份与追捕', description: '体力决定撤离选择，庇护决定你能否在场解释；线索决定交涉是否有依据。', beginnerTip: '先核实鱼的特征和来意，不要把追捕者的一句保证当作全部事实。' } }, [
  s('rain', '雨盖住了气味', '山洞口', ['你跌进洞里，雨水沿胡须滴到石上。洞外的脚步迟疑了一会儿，终于远去。', '更重的一道影子挡住洞口。君寻秋低头嗅你，开口叫的是孩子。'], [c('accept', '先接受她的庇护', 'den', { resources: { shelter: 1 } }), c('explain', '试着说明自己只是路过的猫妖', 'identity', { clues: ['主动表明身份'], trust: 4 })]),
  s('den', '与条纹不一样', '洞内', ['君洲把干草推到你身旁，君潮递来水。两位成年虎妖似乎都知道你紧张。', '你可以先缓过来，也可以立刻寻找第二个出口。'], [c('sleep', '休息并记住洞口位置', 'identity', { resources: { stamina: 2 }, clues: ['洞口路径'] }), c('scout', '查看岩缝通向哪里', 'identity', { resources: { stamina: -1 }, clues: ['岩缝退路'] })]),
  s('identity', '认错与被留下', '洞内火旁', ['君寻秋不愿听你把身份说清，君洲却认真看了看你。话题是否继续，还在你手里。', '有人认错，并不等于你只能一直假扮下去。'], [c('tell_jun', '单独向君洲说明追捕经过', 'border', { clues: ['主动表明身份'], resources: { shelter: 1 } }), c('wait', '把解释留到天晴', 'border', { resources: { stamina: 1 } })]),
  s('border', '林边的气味', '洞外', ['雨停后，你走到熟悉的树旁。泥地上留下了人靴印，也留下山中巡行的爪印。', '此刻还不知道外面是撤退，还是换了一条路等你。'], [c('tracks', '沿外围核对人靴印', 'pack', { resources: { stamina: -1 }, clues: ['巡查路线'] }), c('together', '请君洲陪同试探边界', 'pack', { resources: { shelter: -1 }, clues: ['结伴路线'] })]),
  s('pack', '山中并不空', '林间', ['一群狼妖截住去路，先闻到你身上的山君气味。它们提起君寻秋常将旁的妖认作孩子。', '这是旁人的说法，能解释一部分遭遇，却不能替你定义她。'], [c('ask', '追问它们何时见过追捕者', 'return_path', { clues: ['追捕者仍在山中'], resources: { stamina: -1 } }), c('leave', '趁对方愿意放行，回洞再议', 'return_path', { clues: ['山君误认的传闻'] })]),
  s('return_path', '有人在等你', '林间岔口', ['君洲的身影挡在岔口旁，白袍从树后显出来。你来不及多说，先看见他绷紧的肩背。', '监天司要带走的是猫妖小橘。站在他身后，只能多争取片刻。'], [c('step', '站到能被看见的位置，确认他们找谁', 'fish', { resources: { shelter: 1 }, clues: ['监天司身份陈述'] }), c('hide', '藏在树后，听完整个指控', 'fish', { clues: ['监天司身份陈述'], resolve: -2 })]),
  s('fish', '不是普通鲤鱼', '林间对峙', ['官员说那是国师寻来的文鳐鱼，用来为皇帝治病。你终于想起，那两条鱼长着翅膀。', '对方气急，承诺你仍有用处，不会要你的命。承诺与可验证的事实，必须分开。'], [c('features', '将翅膀特征与文鳐鱼说法对照', 'terms', { clues: ['鱼有翅膀', '文鳐鱼之说'] }), c('guarantee', '先要求解释入京后要做什么', 'terms', { clues: ['未说明的入京用途'] })], q('investigation', '哪一句能自行核对，哪一句仍是单方保证？', '你见过鱼的形态；宫里的用途还只能听对方说。')),
  s('terms', '所谓不会伤害', '山道', ['官员愿意说明奉命办案，却不愿写下交接条件。君洲站得更近了一点。', '你可以用有限庇护争取时间，也可以立即离开。'], [c('delay', '以核验身份为由要求缓行', 'mother', { resources: { shelter: -1 }, clues: ['暂缓带离'] }), { ...c('run', '消耗体力沿岩石退开，寻找下山的路', 'escape', { resources: { stamina: -2 } }), legacyTexts: ['消耗体力退向熟悉的岩缝'] }, c('call', '公开呼唤君寻秋，留在原地', 'mother', { trust: 3 })]),
  s('escape', '脚下的碎石', '山缝', ['你越过岩石，气息乱了。离开追捕者，也意味着离开可以替你作证的人。', '前方有下山路，身后仍听得到君洲的声音。'], [c('rejoin', '折回与君洲会合', 'mother', { resources: { shelter: -1 } }), c('depart', '独自下山，暂避追捕', 'ending_wander')]),
  s('mother', '先别叫我孩子', '山道风口', ['君寻秋到来，风压低草叶。你必须趁双方都安静，决定是继续借误会遮身，还是说出名字。', '她如何回应并不能由你控制，但这句话属于你。'], [c('name', '说出小橘的名字与猫妖身份', 'proof', { clues: ['共同确认身份'], resources: { shelter: 2 }, trust: 5 }), c('silence', '请她先让双方退后再谈', 'proof', { resources: { shelter: 1 } })]),
  s('proof', '两条鱼留下的问题', '临时谈判处', ['吃鱼、追捕与入京用途挤在同一场争执里。哪些已经核实，哪些仍是对方的说法，需要分别看清。', '对方等待你的答复。'], [c('separate', '核对鱼的来历，要求用途另行证明', 'decision', { clues: ['责任与处置分离'] }, { allClues: ['鱼有翅膀', '文鳐鱼之说'] }), c('verify', '要求在山中等待可核验的文书', 'decision', { clues: ['书面核验要求'], resources: { shelter: -1 } }), c('withdraw', '暂不承诺入京', 'decision', { resolve: 3 })], q('deduction', '承认吃鱼，是否等于同意未知的入京安排？', '核实自己的行为与核实对方的处置，是两项独立判断。')),
  s('decision', '同行的条件', '山道', ['追捕没有凭空消失，山君也不能替你把事情忘掉。你们能争取的，是有人同行、用途公开和随时复核。', '君洲问你愿意走哪条路。'], [c('negotiate', '提交核验条件，争取陪同交接', 'review', { clues: ['陪同交接'], resources: { stamina: -1 } }, { anyClues: ['责任与处置分离', '书面核验要求'] }, { tone: 'success', text: '你提交核验要求，对方接受由见证者陪同交接；入京用途仍待证明，没有因此成为已核实的事实。' }), c('stay', '留在山中等待复核', 'review', { clues: ['留山复核'] }), c('leave', '独自离开双方视线', 'ending_wander')]),
  s('review', '这次有人问你的意思', '洞口', ['君寻秋没有替你回答。你第一次发现，洞口可以同时是住处与出口。', '身份是否已经共同确认，要看先前有没有说清；要不要留下，还需要你自己的答复。'], [c('family', '以自己的名字接受庇护', 'ending_home', undefined, { allClues: ['共同确认身份', '留山复核'] }), c('envoy', '与见证者同行赴约', 'ending_terms', undefined, { allClues: ['陪同交接'], resources: { shelter: { min: 1 } } }), c('wander', '保留记录，暂离这座山', 'ending_wander')]),
  e('ending_home', '不必长成另一种模样', ['追捕案仍待复核，君寻秋却在干草旁替你留出了位置。', '你没有长成老虎。有人终于用小橘这个名字，请你留下。'], 'hopeful'),
  e('ending_terms', '有人与你同行', ['你带着列明核验要求的纸，君洲走在你身侧。陪同已经谈妥，入京用途与后续交接仍要逐项得到明确答复。', '京城尚远，这是一段附有条件的同行，不是原作未给出的结局。'], 'uneasy'),
  e('ending_wander', '山外还有雨', ['你避过这一轮带离，也暂时离开了可以继续当面交涉的人。山中仍有人等一声回信。', '你继续走，知道这一次的自由带着尚未处理的责任。'], 'uneasy'),
]);

interface Trial {
  title: string; place: string; scene: string[]; inspect: string; rush: string;
  evidence: string; question: string; hint: string; answer: string; error: string;
  finding: string; aftermath: string[];
  outcomes: { answer: string; error: string; defer: string };
}
// Compatibility-only v1 topology. New games enter handwritten exclusive routes.
function legacyMission(meta: Parameters<typeof make>[0], trials: Trial[], endings: [SceneNode, SceneNode, SceneNode]): AuthoredWorld {
  const [effort, reserve] = meta.resources;
  const entries: SceneNode[] = [s('arrival', meta.title, trials[0].place, meta.intro, [
    c('prepare', `检查${effort.label}与记录用具`, 'field_0', { resources: { [effort.id]: 1 } }),
    c('coordinate', `先确认${reserve.label}的分配`, 'field_0', { resources: { [reserve.id]: 1 } }),
  ])];
  trials.forEach((trial, i) => {
    const field = `field_${i}`, puzzle = `puzzle_${i}`, aftermath = `aftermath_${i}`;
    entries.push(s(field, trial.title, trial.place, trial.scene, [
      c(`inspect_${i}`, trial.inspect, puzzle, { clues: [trial.evidence], resources: { [effort.id]: -1 } }, undefined, { tone: 'success', text: `你留下了「${trial.evidence}」，还需要判断它能支持什么。` }),
      c(`rush_${i}`, trial.rush, puzzle, { resources: { [reserve.id]: 1 } }, undefined, { tone: 'neutral', text: `你先完成眼前的保留行动，没有核查「${trial.evidence}」。这次经过还不能当作调查记录。` }),
    ], q('investigation', `本次调查：${trial.evidence}`, `调查消耗 1 点${effort.label}；保留行动可以补充${reserve.label}，但会少一份可用证据。`)));
    entries.push(s(puzzle, trial.question, trial.place, [trial.scene[trial.scene.length - 1], '眼前仍有一项判断要作。核查过的部分才有据可查，未核查的部分不能凭印象填上。'], [
      { ...c(`answer_${i}`, trial.answer, aftermath, { clues: [trial.finding], resolve: 4 }, { allClues: [trial.evidence] }), feedback: { tone: 'success', text: `${trial.outcomes.answer} 已确认：${trial.finding}。` } },
      { ...c(`error_${i}`, trial.error, aftermath, { resolve: -7, resources: { [reserve.id]: -1 } }), feedback: { tone: 'setback', text: `${trial.outcomes.error} 这次判断没有成立，未取得核对结论。${trial.hint}` } },
      { ...c(`defer_${i}`, '证据不足，暂不下结论', aftermath, { resolve: -1 }), feedback: { tone: 'neutral', text: `${trial.outcomes.defer} 这一轮没有形成结论。` } },
    ], q('deduction', trial.question, trial.hint)));
    entries.push(s(aftermath, i === trials.length - 1 ? '把判断带到行动里' : '行动之后', trial.place, trial.aftermath, i === trials.length - 1 ? [
      c('earned_ending', endings[0].title, endings[0].id, undefined, { allClues: trials.slice(-2).map(item => item.finding), resources: { [reserve.id]: { min: 2 } } }),
      c('partial_ending', endings[1].title, endings[1].id, undefined, { anyClues: trials.map(item => item.finding) }),
      c('withdraw_ending', endings[2].title, endings[2].id),
    ] : [
      c(`recover_${i}`, `用 1 点${reserve.label}换取整备，恢复 2 点${effort.label}`, `field_${i + 1}`, { resources: { [reserve.id]: -1, [effort.id]: 2 } }),
      c(`advance_${i}`, `保留${reserve.label}，立即进入下一处`, `field_${i + 1}`),
    ], q('resource', i === trials.length - 1 ? '哪一种收场与你掌握的证据相符？' : '整备还是继续推进？', i === trials.length - 1 ? `完整路线需要最后两项推理成立，并保留至少 2 点${reserve.label}。部分证据也有独立收场。` : `不要将${effort.label}耗到无法调查；${reserve.label}也是最后行动的必要条件。`)));
  });
  return make(meta, [...entries, ...endings]);
}

const sixRoots = legacyMission({ id: 'six-roots', storyId: '1760265980192886784', title: '学科修仙', author: '六酒', player: '苏砚青', role: '成年外门弟子', summary: '语数外、物化生，竟是这个世界的六大灵根。擂台上，算错不是扣分，答对也不能替同门决定是否继续受伤。', objective: '拆解擂台的题目与规则，保住同门和宗门的选择权。', intro: ['你在考试结束后穿越到逍遥宗。师父只盼这次仙境大选能赢一场。', '大师兄的第一道风刃，问的是二乘三。你终于知道，这里的修为为何分成六门学科。', '本局你与参赛者均为成年人；题目可实际作答，后半段赛事及结局为原创。'], note: '开头摘要与正文的算式分别为减三、减九；本局采用正文擂台的减九，不将两式混为一题。', resources: [r('focus', '专注', 5, 7, '核题消耗，可用宗门支援恢复。'), r('support', '支援', 4, 7, '用于休整与最后的护场行动。')], mechanics: { title: '四轮擂台', description: '先核题，再提交答案。错答消耗支援；最后两轮的证据和余下支援决定能否完整护场。', beginnerTip: '乘除同级，从左到右。原作摘要与正文有不同算式，本局题目以正文现场为准。' } }, [
  { title: '风刃上的算式', place: '青云宗擂台', scene: ['大师兄连问几道乘法，庆尧都答得从容。随后对方将四乘八除以二减九打进一道剑气。', '你看见大师兄迟疑。他会乘法，却没有把运算次序连起来。'], inspect: '逐个抄下运算符与括号情况', rush: '先把支援留给大师兄', evidence: '现场算式 4×8÷2−9', question: '这道剑气的答案是多少？', hint: '没有括号，乘除从左到右，最后减九。', answer: '7：三十二除以二，再减九', error: '13：把减九误记为减三', finding: '混合运算解法', outcomes: { answer: '你依照现场算式写出每一步，同门核对后收下了这份解法。', error: '你报出的数与台上的算式不符，同门只得花掉一份支援照应大师兄。', defer: '你没有提交答案，只留意大师兄的处境；这道题的解法仍未确认。' }, aftermath: ['擂台边的同门还在看着大师兄。刚才有无答对，都不能代替查看他此刻的状况。', '下一场的对攻已经开始，这次符号变成了陌生的音节。'] },
  { title: '不只是问候', place: '第二轮擂台', scene: ['二师姐勉强回应了问候，对手随即问出新的句子。字母在空中结成枷锁。', '句子是 What’s your name?，不是刚才的 How are you?。'], inspect: '核对疑问词与 name 的含义', rush: '先为二师姐留出退场支援', evidence: '姓名问句', question: '怎样回应这句英咒？', hint: '对方问的是姓名，不是近况。', answer: 'My name is Su Yanqing.', error: 'I am fine, thank you.', finding: '姓名应答', outcomes: { answer: '你用姓名回应问句，把它与先前的问候分别记下。', error: '问候没有回应姓名之问。你没能解开这道英咒，同门动用支援照应二师姐。', defer: '你没有替二师姐作答，姓名问句的应答仍留待核对。' }, aftermath: ['字母的余光从台边掠过，二师姐仍需要有人照应。', '最后一位师兄已经上场，对手提起去年的灵药旧怨。'] },
  { title: '不是同一首诗', place: '第三轮擂台', scene: ['宋沐倒地之后，周阳还要继续出拳。你跃上台挡在师兄身前。', '拳风里是“几处早莺争暖树，谁家新燕啄春泥”。你必须接住这一首，而不是前一道题。'], inspect: '辨认当下拳风中的诗句', rush: '先催促同门准备抬走伤者', evidence: '钱塘湖春行来句', question: '应接哪两句化解这一击？', hint: '留意春景里的花、草、马蹄，不要串到送别诗。', answer: '乱花渐欲迷人眼，浅草才能没马蹄', error: '我寄愁心与明月，随君直到夜郎西', finding: '护场诗答', outcomes: { answer: '你接上同一首诗，拳风被化解，护场应答有了可核对的依据。', error: '你串到了另一首诗，没能凭应答化解拳风，只得耗用支援退到台边。', defer: '你没有强接诗句，先从拳风正面退开；这一击没有成为你的护场成绩。' }, aftermath: ['台边仍能感到刚才拳风的余震，倒地的宋沐还没有起身。', '裁判终于走近，接下来必须把继续比试与处理违规分开。'] },
  { title: '胜一场还是保一人', place: '擂台边', scene: ['师父担心连续失利后的除名。周阳曾在对手昏迷后继续出手，这件事有许多人看见。', '游戏从这里进入原创分支：你要凭什么要求暂停，不能只说自己记得更多诗。'], inspect: '核对倒地时刻与追加攻击的目击', rush: '保留支援，先护住场边的人', evidence: '倒地后追加攻击记录', question: '哪项理由足以支持先暂停？', hint: '胜负压力不改变追加攻击已发生的事实；把具体时刻与见证人提交。', answer: '以昏迷后的追加攻击申请暂停并救助', error: '只要我会更多题，对手的攻击便自动无效', finding: '护场申诉依据', outcomes: { answer: '你将追加攻击的时刻与见证人提交裁判，以此申请暂停和救助。', error: '你用答题能力代替违规依据，申诉没能成立，还耗去了同门的支援。', defer: '你暂不提交申诉，追加攻击尚未形成这一轮可用的裁定依据。' }, aftermath: ['裁判站在台边，题目的胜负与伤者的处境都摆在眼前。申请是否有据，要看刚才实际核过什么。', '同门等待你的最后决定。'] },
], [e('ending_team', '留住上台的选择', ['最后两轮的答题与申诉都站得住脚，你用留下的支援把伤者送离擂台。', '宗门的命运仍待正式裁决，但没有人再被迫靠挨下一拳证明自己。'], 'hopeful'), e('ending_notes', '把解法带回山门', ['你没有把整场大选扭转，却带回至少一项核对所得。尚未答出的题与未核实的见证，仍留着缺口。', '回山后的第一堂课，从分清题目与运算顺序开始。'], 'uneasy'), e('ending_leave', '先离开擂台', ['你放弃当场争胜，带同门退出这一轮。宗门的处境更加艰难。', '留住性命之后，仍有许多没有答完的问题。'], 'uneasy')]);

const palaceLedger = legacyMission({ id: 'palace-ledger', storyId: '1793742089336532992', title: '00后整顿后宫', author: '苏荔', player: '朱玉润', role: '掌握娘家分红的成年皇后', summary: '失宠并未抹去你付出的嫁妆。宫中的尊荣、钱款和服侍被混成一笔账，你要重新划清每一项的界限。', objective: '以可核对的账目停止无止境索取。', intro: ['你穿成朱玉润。皇帝嫌弃，太后使唤，娘家的分红却每月仍到。', '眼前的麻烦过去之后，小英捧来装孝敬的空匣。你才知道送钱之外，还要每日去捏脚。', '本局从账目和宫务展开原创分支，不复演原文的自伤与危险解释。'], note: '保留皇后、朱家资助、分红、太后索取与小英；新增账目核验和宫务谈判。', resources: [r('energy', '精力', 5, 7, '核账与取证消耗。'), r('silver', '银票份额', 4, 7, '整备和维持独立宫务需要资金。')], mechanics: { title: '宫务与账目', description: '核查支出用途，辨认自愿赠与和强制索取；保留银票才能兑现最后的独立安排。', beginnerTip: '先看款项用途和收讫记录。把钱留在手里不等于已经证明每一项主张。' } }, [
  { title: '一个空匣子', place: '皇后寝宫', scene: ['小英把空匣推到你面前，提醒你以往会拿大半分红孝敬太后。', '她说得太熟练，像在重复一条从未有人核对的规矩。'], inspect: '让小英列出过去每月的交付', rush: '先把本月银票封存', evidence: '历月分红交付记录', question: '过去一直交付，能证明什么？', hint: '惯例能证明发生过，不能单独证明不可撤回的义务。', answer: '证明过去发生过，需要另核依据与用途', error: '证明以后永远必须照同样比例交付', finding: '惯例与义务区分', outcomes: { answer: '你在交付记录旁另留依据与用途栏，没有把旧惯例直接续成永久义务。', error: '你把惯例说成了不可撤回的承诺，本月又划出一份银票，却没有厘清依据。', defer: '你暂不判断旧惯例的约束，交付是否应当继续仍悬着。' }, aftermath: ['空匣仍在小英手里，以往的交付还没有替今天所有问题作出回答。', '接下来要核对的，是嫁妆与宫中对朱家的说法。'] },
  { title: '一车车填进国库', place: '宫中账房', scene: ['朱家嫁妆曾用于填补国库。入宫三年，这笔资助却常被说成皇家的恩赐。', '你不打算靠一句更响的斥责补齐记录。'], inspect: '查找嫁妆用途与入库记录', rush: '保存资金，先不调取旧册', evidence: '嫁妆入库记载', question: '什么材料能支持朱家确曾资助？', hint: '查资金去向与收讫，身份高低不是账目证据。', answer: '日期、数量、用途和收讫对应', error: '只要朱家有钱，任何数额都可以直接主张', finding: '朱家资助依据', outcomes: { answer: '你将旧册的日期、数量、用途和收讫逐项对应，资助主张有了明确范围。', error: '你提出了没有逐项对应的数额，争执耗去一份银票，却没有增加可核对的凭据。', defer: '你暂不提出资助数额，没有完成的核对仍留待之后。' }, aftermath: ['账房里堆着历年的旧册。家中的钱曾经去过哪里，需要凭据逐项回答。', '太后催促的口信又到了，宫里的劳动同样需要一条界限。'] },
  { title: '每天去捏脚', place: '太后宫外', scene: ['你过去既送钱又亲自服侍。现在一停下来，责备便说你忘恩负义。', '你准备把身体与时间从款项争议中单独拿出来谈。'], inspect: '核对服侍安排与实际宫务职责', rush: '留出银票支付正常宫务', evidence: '宫务与额外服侍清单', question: '哪种安排能真正停止无止境索取？', hint: '明确拒绝新增要求，同时安排正式职责，不以再讨好一次换未来宽容。', answer: '列明宫务职责，拒绝额外强制服侍', error: '这次加倍服侍，期待以后对方自己改变', finding: '劳动边界', outcomes: { answer: '你把正式职责与拒绝的额外要求写清，交给小英转达并记录回应。', error: '你答应加倍服侍，时间与银票又搭了进去，额外要求却没有因此停止。', defer: '你暂未提出新的服侍界限，正常宫务与额外要求仍需另行议定。' }, aftermath: ['催促声还在宫门内响着。小英看着你，等下一步安排。', '要让今后的日子按约定运转，仍需资金、接收人和明确时限。'] },
  { title: '锦盒留在哪边', place: '宫门', scene: ['嬷嬷要求先把本月孝敬放下。小英下意识向前一步，又回头看你。', '娘家的资助与额外劳动的要求是两件事；每一件有多少凭据，还要分别核实。'], inspect: '将资助凭证和宫务清单交叉核对', rush: '优先保留寝宫运转资金', evidence: '款项与职责分表', question: '如何提出可执行的新安排？', hint: '分别说明钱与职责，要求书面回应；不能靠辱骂代替具体条款。', answer: '停止无依据上缴，公开正常宫务费用并要求签收', error: '把所有经手者都认定有罪，无需区分用途', finding: '独立宫务方案', outcomes: { answer: '你提出停止无依据上缴，并将正常宫务费用单列，请接收者签明回应。', error: '你把所有经手者一并指责，具体费用反而无从讨论，交涉又耗去一份周转。', defer: '你没有提交新的宫务方案，锦盒的用途与费用界限仍未谈妥。' }, aftermath: ['锦盒摆在宫门两侧的目光之间。争论至今，并不等于新安排已经生效。', '小英等你决定，这个锦盒今后用来装什么。'] },
], [e('ending_budget', '自己的宫务账', ['你保留足够周转，凭最后两项核验落实新安排。钱的去向、宫人的职责都有了可复查记录。', '争执没有一夜消失，但你的日子终于有了不靠讨好维持的边界。'], 'hopeful'), e('ending_receipts', '留下不被改写的账', ['完整安排暂时未能落实，你仍保住一部分可核对的凭证。', '下一次同样的要求到来，你可以从已核过的部分谈起，余下争议仍需补证。'], 'uneasy'), e('ending_pause', '关上宫门整顿', ['你暂停交涉，先安排寝宫眼前的生活。外面的议论继续，旧账尚未厘清。', '这是一段暂退，不能冒充争议已经解决。'], 'uneasy')]);

const redPlum = legacyMission({ id: 'red-plum', storyId: '1930445234262750503', title: '俺妈和她的丧尸闺女', author: '归像', player: '王红梅', role: '保护成年女儿的母亲', summary: '村里需要你的菜棚，也需要闹闹驱退丧尸。留下女儿不等于否认危险，帮助邻里也不该把她当作工具。', objective: '在物资、信任和女儿的安全之间建立共同生活规则。', intro: ['你从外地回村，找到了已经变成丧尸的女儿闹闹。你不肯放弃她。', '菜棚使幸存者留下，也使争执聚到你家门口。有人来换菜，有人想赶她走，还有人夜里来借她驱退丧尸。', '本局闹闹明确成年。针灸和驱尸属于原作幻想设定，游戏只处理资源、记录与外出边界。'], note: '本局不将幻想针灸改写成现实疗效，不提供针法或药方；照料公约和撤离路线为原创。', resources: [r('strength', '体力', 5, 7, '菜棚、记录与走访消耗。'), r('food', '菜粮', 4, 7, '支撑整备、交换与共同值守。')], mechanics: { title: '菜棚与照料', description: '调查冲突要花体力，值守与整备要花菜粮。把个体观察与普遍承诺分开。', beginnerTip: '留下闹闹的具体反应记录，先确认外出条件，再决定是否帮助邻里。' } }, [
  { title: '村口的交换', place: '菜棚', scene: ['白菜换盐，萝卜换火柴。你又换了半瓶辣酱，因为闹闹还尝得出辣味。', '胡医生再次提醒危险，几位邻居却只看着菜棚是否还能供应。'], inspect: '记录需求、存量与交换承诺', rush: '先多留一份菜粮在家', evidence: '菜棚供应清单', question: '什么安排能撑过下一周？', hint: '交换数量要与存量和日常消耗相符，不能把田里未来的收成全部许出去。', answer: '按现有存量分配并保留家庭份额', error: '先答应所有人，等收成时自然能补齐', finding: '可持续配给', outcomes: { answer: '你照着存量划出家庭份额，再请人把可交换的数目写在门板上。', error: '你答应了超过眼前存量的请求，只得先动用家里的菜粮，缺口却仍没有着落。', defer: '你没有定下下一周的配给，邻居的请求还不能算作已经落实的份额。' }, aftermath: ['篮里的菜不会因为请求多就自己长出来。门口的人还在等接下来的安排。', '菜地里的动静忽然打断了交谈。'] },
  { title: '抓伤之后', place: '院门', scene: ['一名偷菜的人被闹闹抓伤，众人带着工具围住院门。你护在她身前，手也在抖。', '偷菜与受伤同时发生，承认其中一件不等于可以抹去另一件。'], inspect: '分别核对偷菜经过与受伤时刻', rush: '先备好物资安置双方', evidence: '院门事件经过', question: '怎样处理才不会扩大冲突？', hint: '先安置伤者、隔开接触，再查经过；不要靠否认已经发生的伤害保护女儿。', answer: '隔开双方，处理伤者并保留经过记录', error: '她是我的女儿，所以不可能造成伤害', finding: '隔离与事实核查', outcomes: { answer: '你请双方隔开，把伤者交给人照看，并留下偷菜与抓伤各自的经过。', error: '你的否认使门外更难平静，额外菜粮耗在僵持中，伤害经过没有得到共同确认。', defer: '你暂不判断责任，伤者的处境与闹闹周围的接触仍需要处理。' }, aftermath: ['闹闹蹲在菜筐旁，没有听懂门外的争吵。院门两边都有人等着事情往下解决。', '胡医生把一本空笔记放在桌上。'] },
  { title: '那声模糊的妈', place: '屋檐下', scene: ['闹闹曾短暂清醒，叫出一声妈。你一直把那个音节藏在心里，像藏着一盏灯。', '胡医生希望记录她的日常反应。你可以请人代写，也可以把愿望当作已经痊愈。'], inspect: '请人代写时间、行为与不同反应', rush: '先为母女留足晚饭', evidence: '闹闹个体观察记录', question: '若只记录到一次反应，它能支持什么结论？', hint: '一次反应属于这个人、这个时刻；它不能证明所有感染者都安全，更不能证明治愈。', answer: '证明出现过特定反应，仍需谨慎观察', error: '证明她已经完全恢复且不会再次伤人', finding: '观察与愿望区分', outcomes: { answer: '你请人只写下发生过的反应，没有出现的进步留为空白。', error: '你把那声呼唤说成痊愈保证，胡医生要求重新核查，周转又耗去一份菜粮。', defer: '你没有给出痊愈与否的判断；未作观察的时段仍缺少记录。' }, aftermath: ['闹闹还在屋檐下，那声呼唤也仍留在你的记忆里。愿望不会自己变成下一次观察。', '夜里的敲门声比以往急，邻居来求闹闹帮忙。'] },
  { title: '两斤腊肉的请求', place: '夜间村道', scene: ['邻居说丧尸扒上了窗户，愿意拿腊肉来换帮助。你给闹闹套上护具，却没有立即放她出去。', '谁同行、走哪条路、何时回来，不能由一份报酬代替。'], inspect: '核对路况、接应人和撤回信号', rush: '把菜粮留作今晚应急', evidence: '夜间出行安排', question: '哪种援助有明确的返回条件？', hint: '协同行动与撤回安排必须在出门前确认；女儿不是借出去就无需照看的工具。', answer: '有人接应、保持距离，约定信号后短程援助', error: '收下腊肉就让她独自去，大家都会照顾她', finding: '有边界的援助', outcomes: { answer: '你让同行的人复述撤回信号，确认有人接应后才答应短程援助。', error: '你让闹闹独自出了门，却无人能说清怎样接应，只得另花菜粮请人把她接回。', defer: '你暂不答应出行，闹闹仍留在灯下，援助的返回条件尚未落实。' }, aftermath: ['屋里的灯仍亮着，村道隐在夜色中。报酬与求助声都不能替接应人守住回程。', '这场末日里的相处，要由活着的人共同承担。'] },
], [e('ending_village', '院门内外都有名字', ['你留下粮食并落实观察、值守与接应，村里开始按约定求援。闹闹没有被宣布治愈，也没有被当作随叫随到的工具。', '夜里她回到灯下，你给她留的饭还温着。'], 'hopeful'), e('ending_watch', '先把今天记下来', ['你保存了部分事实，眼前只能实行较短的探访与交换。', '没有观察的日子仍留着空白。母女暂时留在村子边缘，等待下一次讨论。'], 'uneasy'), e('ending_depart', '推车上的菜苗', ['你决定离开这轮对峙，带上能搬走的菜苗与物资。', '新的住处尚未找到。保护女儿的决定，仍需要一路面对现实代价。'], 'uneasy')]);

const hollowImmortals = legacyMission({ id: 'hollow-immortals', storyId: '1558118587956662272', title: '杀仙成道', author: '满目山河依旧', player: '管彤', role: '能看穿异物的成年弟子', summary: '所谓仙丹藏着虫卵，所谓灵脉连接着丹田中的异物。你还能相信自己的眼睛，却不知道谁愿意听你的证言。', objective: '查清仙门异常，带着可核对的证据离开。', intro: ['你能看透地下水脉，因此被带上蓬莱山。师父给你的仙丹，糖衣下藏着虫卵。', '你假装服药，数月未能筑基。关于故乡的残酷对话，让离开不再只是保命。', '本局管彤明确成年；节选停在长老洞府，之后的取证与逃离均为原创。'], note: '保留魏旻、祁莫、璇玑仙尊及白鹤村事件。不将村民死讯改为可被游戏轻易撤销的假象。', resources: [r('attention', '心神', 5, 7, '透视与取证消耗。'), r('cover', '掩护', 4, 7, '维持伪装与最终撤离的条件。')], mechanics: { title: '仙山取证', description: '观察会消耗心神，错误断言消耗掩护。最后需要把不同观察连成证据链。', beginnerTip: '分清亲眼所见、偷听证言与推测。不要因一种能力就断言已经知道全部阴谋。' } }, [
  { title: '糖衣破开之后', place: '弟子卧房', scene: ['你吐出藏在舌下的丹丸。糖衣破开，透明薄膜里的虫卵正在蠕动。', '火炉就在旁边。要摧毁它还是先留记录，是你第一次需要独自承担的决定。'], inspect: '记下糖衣与卵膜的对应形态', rush: '迅速处理丹丸，保持伪装', evidence: '丹丸虫卵观察', question: '亲眼所见首先能确认什么？', hint: '确认这一枚丹丸的结构；不要跨过尚未核验的分发范围。', answer: '这枚仙丹包藏虫卵', error: '天下所有丹药都相同，无需再查', finding: '仙丹异物记录', outcomes: { answer: '你把结论限定在这一枚丹丸，糖衣与卵膜的结构有了对应记录。', error: '你把单枚所见推广到所有丹药，仓促掩饰又耗去一份掩护，断言仍无从证明。', defer: '你暂未把所见整理成结论，没有核查的部分仍只剩惊疑。' }, aftermath: ['炉火还在跳动。无论有没有留下观察，未筑基的处境都没有因此改变。', '师兄们已经开始询问，你为何还没筑基。'] },
  { title: '所谓两条脉', place: '练功处', scene: ['魏旻说筑基后只会感到灵脉与自脉。他掌中生火，祁莫又将水凝成冰。', '你看见异物与他们所称的灵脉相连。能力是真的，解释却未必完整。'], inspect: '比较异物位置、灵脉与火水能力', rush: '点头应答，减少注视时间', evidence: '异物与灵脉相连', question: '两组观察更支持哪种判断？', hint: '连接关系与能力差异支持共存关联，还不能单凭它判断每个人知不知情。', answer: '能力与体内异物相关，知情程度仍未知', error: '师兄会施法，所以服药必定完全安全', finding: '灵脉关联', outcomes: { answer: '你记下异物与能力的关联，把师兄是否知情留作未知。', error: '你将施法能力当作安全保证，放松警惕后又得补救伪装，仍没有服药安全的依据。', defer: '你暂不解释异物与能力的关系，也没有得到他们是否知情的答案。' }, aftermath: ['师兄掌中的火与冰都曾真实出现，他们怎样理解自身的变化却还未明说。', '去打听下山道路时，你听见熟悉的村名。'] },
  { title: '白鹤村的名字', place: '灌木后', scene: ['祁莫说村民已经被杀，魏旻确认是否留下后患。两人还打算等你筑基后再告诉你。', '你压住呼吸，知道这段话改变了返乡的含义。'], inspect: '记住说话人、村名与关键时序', rush: '先离开听得到脚步的位置', evidence: '白鹤村对话证言', question: '怎样保留这段残酷证言？', hint: '区分听到的具体话语与尚未亲自核实的现场；不替加害者添动机，也不轻易抹去事件。', answer: '明确注明偷听证言及说话人，另寻物证', error: '只要我无法接受，村民就必然仍活着', finding: '村庄事件证言', outcomes: { answer: '你注明祁莫与魏旻的具体话语，将偷听所得与尚未亲见的现场分开。', error: '你一时否认死讯，却拿不出新的事实；稳住情绪、遮掩异样又耗去一份掩护。', defer: '你暂未整理出可提交的证言，那段已经听到的对话仍无法从记忆中抹去。' }, aftermath: ['白鹤村的名字压在你心里。无论刚才如何作答，那些曾给过你饭的人都不会因此变得无关紧要。', '璇玑召你前往大殿，再次询问未筑基的原因。'] },
  { title: '铜柱上的仙宫', place: '长老洞府外', scene: ['你随师父进入蓬莱深处。八十一根铜柱托起仙宫，木窗内却是巨大的异物。', '游戏从这里展开原创撤离：窗内所见要与先前见闻分别核对，尚未记录的部分不能假作现成证据。'], inspect: '核对洞府异物与丹丸、灵脉的共同特征', rush: '记住来路，优先维持掩护', evidence: '洞府异物观察', question: '什么材料能组成可复查的证据链？', hint: '把丹丸、灵脉、洞府观察分别保留，标明可见范围，再与村庄证言分层提交。', answer: '分别记录三处观察与来源，保留未知部分', error: '写成自己已经看穿所有仙门与所有修士', finding: '分层证据链', outcomes: { answer: '你按来源整理能够核对的观察，把缺少早先记录的部分标为待补，证言另列。', error: '你写下超出所见范围的断言，又耗去掩护藏起这份文字；它不能成为完整的证据链。', defer: '你暂不组织证据链，只准备离开；此前没有查过的材料仍然缺失。' }, aftermath: ['你握着冰凉的白玉令牌。大殿外的脚步声再次接近，没有人会为你的准备多等一刻。', '离开需要掩护，而你出去以后能说些什么，要看实际留下了多少证据。'] },
], [e('ending_witness', '带下山的名字', ['你用余下掩护走过最后一道关口，将村庄证言与洞府记录分别封存。', '这没有立刻推翻蓬莱，却使故乡不再只存在于加害者的一段笑谈里。'], 'hopeful'), e('ending_fragment', '残页尚在', ['你带出部分经过核实的记录，证据链仍有缺口。', '山外的人未必立即相信，但你知道下一步需要寻找哪一种证明。'], 'uneasy'), e('ending_escape', '无声下山', ['你舍弃当面争辩，趁缝隙下山。未能带齐的材料留在身后。', '活下来只是第一步，白鹤村的名字仍压在你心口。'], 'dark')]);

const islandBroadcast = legacyMission({ id: 'island-broadcast', storyId: '1783485301039054849', title: '穿成十八线女星我坐鳄鱼全网爆火', author: '不吃鱼的喵', player: '姜眠', role: '误入人类综艺的成年水豚灵魂', summary: '你习惯平静，却被塞进一档恋爱求生直播。镜头、任务与标签各有自己的逻辑，活得自在仍需要作出决定。', objective: '完成真实分工，守住求生与镜头之外的个人边界。', intro: ['你原本是水豚，系统绑定出错后成了姜眠。醒来时，网上已经有了许多关于她的故事。', '恋爱求生节目要在小岛直播。你与谢骁负责寻找食物，其他组负责木柴、物资和床板。', '节选尚未发生标题中的后续场面；本局从已提供的分工与林间观察发展原创玩法。'], note: '所有嘉宾为成年人。本局不虚构已读到坐鳄鱼的正文，也不把节目中的动物亲近描写当作现实接近野生动物的建议。', resources: [r('energy', '精力', 5, 7, '核对任务、调查现场消耗。'), r('supplies', '补给', 4, 7, '用于休整与团队夜间安排。')], mechanics: { title: '直播求生', description: '先核实任务与来源，再回应传闻。保留补给才能把明确分工转成可执行的过夜安排。', beginnerTip: '镜头里出现了什么，不等于镜头外已经证明了什么。分工要先核对接应与物资。' } }, [
  { title: '标签先于本人到场', place: '临时茅屋', scene: ['大家介绍小名，你说卡皮巴拉。有人笑，有人已经替这个名字编好了动机。', '你看不到全部弹幕，眼前能做的，是确认今天实际要完成的任务。'], inspect: '向节目组核对任务与沟通方式', rush: '先整理能用的补给', evidence: '传呼机任务记录', question: '哪一项能作为行动依据？', hint: '区分节目组下达的任务与未经核实的动机猜测。', answer: '经传呼机确认的任务和回报方式', error: '每条弹幕都准确知道当事人的真实意图', finding: '任务来源核验', outcomes: { answer: '你请节目组重复任务地点和回报方式，把传呼机里的答复留下。', error: '你把弹幕揣测当作真实意图，回应标签耗去一份补给，任务来源却仍未核实。', defer: '你暂不判断谁的说法可靠，没有确认的任务细节仍需再问。' }, aftermath: ['黑色传呼机短促地响了一次，镜头仍对着各自收拾行李的嘉宾。', '嘉宾开始分组，你和谢骁走向树林。'] },
  { title: '四组不同的事', place: '林地入口', scene: ['你们找食物，苏苏与秦白捡木棍，王玥与赵景之寻找饮水和器具，最后一组做床板。', '看起来人人都有任务，却还没有人说明在哪里会合、怎样确认缺项。'], inspect: '核对四组产出与会合地点', rush: '先留下一份备用补给', evidence: '四组分工清单', question: '哪项缺失会让分工失效？', hint: '各做各的并不保证水、火和食物在同一地点同一时间可用。', answer: '缺少会合时间、交接地点与缺项回报', error: '只要有人负责食物，其他物资都不必确认', finding: '交接安排', outcomes: { answer: '你补问了会合时间、交接地点和缺项回报，知道带回的东西应交给谁。', error: '你只顾食物便往前走，遗漏交接让团队多耗一份补给，其他物资仍没有核对。', defer: '你暂不认定分工已经齐备，交接的具体条件仍悬着。' }, aftermath: ['谢骁在林地入口停了一下，其他几组已经走向各自负责的地方。', '林间出现了一段与镜头期待不同的安静。'] },
  { title: '停在肩头的身影', place: '树林', scene: ['鸟停在你头顶，松鼠靠近背包。谢骁看着你，嘴角动了一下。', '你熟悉这样的相处，摄像头却正等待一个更刺激的片段。'], inspect: '观察动物距离与离开的路径', rush: '保留补给，继续按任务走', evidence: '林间接近观察', question: '此刻的亲近能推出什么？', hint: '一次接近只说明当下状态，不代表每只动物都可触摸、饲喂或充当运输工具。', answer: '保持空间，让它们自行离开，不扩大成能力保证', error: '所有野生动物都会服从我，可以任意接近', finding: '镜头中的边界', outcomes: { answer: '你留出距离，等它们自行离开，没有把这次接近许诺成每次都能做到的表演。', error: '你夸下可以任意接近的保证，下一次接近却没能兑现，折返又耗去一份补给。', defer: '你没有作出动物会服从的保证，也没有替这次接近给出普遍解释。' }, aftermath: ['林子里仍有各自活动的声音，镜头捕到的一刻已经过去。', '节目组催问收获，你需要解释哪些是实际带回的东西。'] },
  { title: '晚饭之前的回报', place: '集合点', scene: ['茅屋前的物资并没有自动变成晚饭。各组回来后，要重新核对谁带回什么、缺什么。', '这一轮原创行动里，证明你能照顾自己与制造话题，是两项不同的事。'], inspect: '清点实际补给并确认饮水、器具和留守', rush: '保留储备，先不承诺额外安排', evidence: '集合点物资清点', question: '怎样安排今晚才有可执行的余地？', hint: '把已到物资与尚缺物资分别列出，再按任务调配，不能拿热度代替饮水和休息。', answer: '按实际清点分配，缺项通过传呼机求补', error: '先制造热搜，现实缺项以后自然有人解决', finding: '过夜协作安排', outcomes: { answer: '你照实际清点分配已有物资，用传呼机逐项报告缺项，留下过夜安排。', error: '你先去制造话题，等待中又耗去一份补给，未处理的物资缺项并没有自行补齐。', defer: '你暂不承诺今晚的完整安排，缺项仍需核实，晚饭也不能算已经准备好。' }, aftermath: ['天色渐暗，茅屋前摆着这一轮带回的东西。接下来能否开饭，还要看清点与安排实际落实到哪一步。', '镜头还亮着，这次你有自己的回答。'] },
], [e('ending_team', '镜头之外的晚饭', ['你们凭清点与补给把过夜安排落实。谁都可以开口说缺什么，也可以拒绝额外表演。', '流量怎样变化尚未确定，但你吃到的这一顿是真实的。'], 'hopeful'), e('ending_record', '一份完整的当日记录', ['你把当日的核验与空缺一并列在记录里。团队仍有缺项需要节目组介入，写全经过不等于完成了所有任务。', '至少今天的经历，不必全部交给旁人的标签解释。'], 'uneasy'), e('ending_rest', '暂停镜头', ['你停止继续加码，要求先休息并处理未确认的物资。节目效果受到影响。', '这一局没有承诺爆红，只留下一个可以重新商量的明天。'], 'uneasy')]);

const wrongRealm = legacyMission({ id: 'wrong-realm', storyId: '1716453753710972928', title: '我在修真界掏出了AK47', author: '风吹过你的心窝', player: '叶青青', role: '被传送错世界的成年任务者', summary: '你为星际准备的仓库被带进修真界。力量差距改写了擂台，却不能自动还原被同门扭曲的旧事。', objective: '保住修复灵根的药材，用证据结束被迫让步。', intro: ['系统把星际任务传成了修真任务。你灵根受损，辛苦带回的玉灵芝又被要求让给师妹苏沁沁。', '擂台已经失控。你有科幻护身屏与大量仓储，但这一局要解决的不只是赢下一次交手。', '后续的记录、申诉与离宗安排为原创，武器仅以虚构战斗结果呈现。'], note: '保留受损灵根、玉灵芝、偏袒规则、系统错投与护身屏。不提供现实武器制作或操作细节。', resources: [r('charge', '护屏能量', 5, 7, '保护调查和稳定现场消耗。'), r('reserve', '仓储配额', 4, 7, '补充护屏与最后撤离使用。')], mechanics: { title: '护屏与宗门规则', description: '能量与仓储有取舍；核对药材来历、救援旧事与擂台规则，才能改变处置条件。', beginnerTip: '有力量不等于已有证据。留下至少两份后段推理依据和撤离配额。' } }, [
  { title: '错误的任务位面', place: '擂台屏障内', scene: ['系统承认把你传错世界，却说只要熬到结局都一样。仓库里明明是为星际准备的物资。', '你先要确认自己拥有什么，不能任由一句“炮灰剧本”定义全部选择。'], inspect: '核对系统任务与实际仓储', rush: '保留一份仓储应急配额', evidence: '任务与位面不符', question: '系统的错误意味着什么？', hint: '错误投送改变了条件，不会自动证明你必须接受所有既定羞辱。', answer: '重新核验生存目标与实际可用资源', error: '被叫作炮灰就只能放弃所有选择', finding: '任务条件重核', outcomes: { answer: '你把生存目标与可用仓储重新对应，不再照系统对角色的称呼安排全部行动。', error: '你照着炮灰的说法停下判断，维持僵局又耗去一份仓储，任务条件仍没有核清。', defer: '你暂不解释错投带来的全部影响，还没有形成新的任务判断。' }, aftermath: ['护屏隔开擂台上的压力，系统的提示仍不能替你决定下一步。', '苏沁沁仍在索要那株药，它的来历成为眼前的争点。'] },
  { title: '苦寒地带回的药', place: '擂台边', scene: ['玉灵芝是你冒险带回、用来治疗受损灵根的药。苏沁沁要它巩固修为，师尊还借出了本命剑。', '两种需求被一句“不过一株药”压成一样，你不准备接受这个说法。'], inspect: '核对药材取得经过与双方用途', rush: '先保全剩余仓储', evidence: '玉灵芝来历与用途', question: '为什么不能把双方需求简单等同？', hint: '修复损伤与巩固修为不同，取得成本和归属也需要单独核对。', answer: '分别核对损伤治疗、修为巩固与药材归属', error: '别人更受欢迎，就自然获得药材所有权', finding: '药材归属依据', outcomes: { answer: '你分别列出治疗、巩固修为与取药经过，使归属主张有了具体依据。', error: '你顺着偏爱的说法承认对方有权索药，交涉耗去一份仓储，药材归属仍没有得到核验。', defer: '你暂不作归属结论，药材用途与取得代价仍待放在一起核对。' }, aftermath: ['那株药仍是争执的中心，周围的人又开始搬出秘境里的旧事。', '那一次谁引开妖兽、谁得到救援，正是下一项要核实的事实。'] },
  { title: '谁没有回来接应', place: '擂台记录处', scene: ['你为掩护同门引开妖兽，灵根因此受损。众人却将逃生功劳都归给苏沁沁。', '你不能靠同样的偏袒来反击，必须逐一核对先后发生的行动。'], inspect: '整理引开追击、撤离与未获接应的时序', rush: '保留配额以防再次施压', evidence: '秘境撤离时间线', question: '如何判断谁承担了什么代价？', hint: '分别记录引开危险、撤离工具和接应缺失，多项行动可以同时存在。', answer: '依据时间线区分掩护、撤离和缺失的接应', error: '只要师妹提供过工具，其他人的付出都归零', finding: '救援责任区分', outcomes: { answer: '你按先后次序标出掩护、撤离和未获接应，没有用一人的行动抹掉另一人的代价。', error: '你用撤离工具抹去其他付出，争论又耗去仓储，却没有厘清谁承担过什么。', defer: '你没有完成救援责任的区分；未经整理的经过还不能充作已核对的时间线。' }, aftermath: ['受损的灵根仍隐隐作痛。台边不同的说法，都无法自行补回当时缺失的接应。', '明渊的介入已经让擂台规则变成第二个争点。'] },
  { title: '上台是否算参战', place: '比武台', scene: ['宗门规则允许上台者替一方打擂。明渊上台动手后，又说自己没有参加。', '你记得规则如何被用来索取玉灵芝，今天也必须按同样标准核验。'], inspect: '将上台、动手与替战条款对应', rush: '保存仓储以便结束对峙', evidence: '替战条款与现场记录', question: '怎样要求一致适用规则？', hint: '把同一条款应用于相同的行为，保留申诉与见证，不能先改结果再挑规则。', answer: '以实际参战行为核对替战责任，提出统一裁定', error: '只看谁的师尊更强，再倒过来解释规则', finding: '一致裁定依据', outcomes: { answer: '你将上台与动手的记录同替战条款对应，请见证者按相同标准核对。', error: '你按师尊强弱解释规则，对方也据此争执，仓储再次消耗，统一裁定仍无依据。', defer: '你暂不提出规则裁定，没有核验的现场行为仍需另留见证。' }, aftermath: ['护屏仍亮着，擂台上的争执没有自行结束。能交给见证者的，是实际留下并核对过的部分。', '现在需要决定，留多少力量用于交涉，留多少用于离开。'] },
], [e('ending_departure', '带着自己的药离开', ['最后两项依据完整，仓储也足以保护撤离。你带走玉灵芝，将争议记录交给外部见证。', '修复灵根仍需时间，但你不再以接受羞辱作为活到结局的条件。'], 'hopeful'), e('ending_claim', '未被删掉的申诉', ['你留下部分可核对材料，暂时退出这一轮对峙。', '宗门还没有承认全部责任，然而你已不必只靠更大的声响证明自己存在。'], 'uneasy'), e('ending_shield', '护屏外的山门', ['你把最后的注意力用于撤离，争议未能在现场厘清。', '山门远去，尚未厘清的争议与未恢复的灵根仍跟着你。'], 'uneasy')]);

export const catalogWorldsB: AuthoredWorld[] = [templeHeart, tigerShelter, sixRoots, palaceLedger, redPlum, hollowImmortals, islandBroadcast, wrongRealm].map(expandCatalogB).map(polishBChoices).map(correctBLiveProse).map(withCatalogBEditorial);
