import type { SourcePassage } from '../shared/types.ts';

export const coreSourcePassages: Record<string, SourcePassage[]> = {
  'blue-blood': [
    {
      id: 'blue-training-colour',
      label: '培训中的血色常识',
      quote: '培训师指着模型说：「记住，人的血液是蓝色的，接触空气后才会慢慢氧化变红。」',
      nodeIds: ['training', 'mirror', 'desk'],
      clues: ['变色观察记录'],
      note: '原文以培训中的血色常识和洗手间观察引出异常；游戏中的选择、记录方式与后续调查为改编，血色说法属于故事世界设定。',
    },
    {
      id: 'blue-directed-test',
      label: '只出现在她卷上的问题',
      quote: '而我的，第一题是：人的血液是什么颜色？',
      nodeIds: ['test', 'case_paper', 'case_inference'],
      clues: ['差异试卷', '定向试题记录'],
      note: '原文对照同事的急救题与主人公的常识题；游戏压缩了考试发生的时间，并新增姓名栏、原件留存、联络补证和深夜复核，不能由此推定全体同事知情。',
    },
    {
      id: 'blue-shifted-landmark',
      label: '地标与记忆的错位',
      quote: '东方明珠塔的简介上写着：位于北京朝阳区的标志性建筑，建成于 2008 年北京奥运会前。',
      nodeIds: ['browser', 'case_map', 'forum', 'evidence_review'],
      clues: ['地标错位记录', '独立地理对照'],
      note: '原文提供地标城市错位及匿名提问的开端；游戏新增分栏保存、独立复核、第二位见证者与跨界结局，节选未给出匿名提问之后的结果。',
    },
    {
      id: 'blue-observer-disappearance',
      label: '走进死胡同的人',
      quote: '但灰夹克从我面前走过后，我等了很久，他却始终没有回来。',
      nodeIds: ['transit', 'diner', 'alley', 'station', 'case_witness', 'observer', 'coordinate'],
      clues: ['观察者行程', '消失巷口照片', '反应与观察时序'],
      note: '原文写到灰夹克的反复出现与在死胡同消失；游戏新增地铁求助、巷口照片、倒影参照和当面交谈，照片线索及通过边界的结果均不是原文已有证据。',
    },
    {
      id: 'blue-reaction-hypothesis',
      label: '针对反应的试探猜想',
      quote: '对，他们现在的行动，是基于我的反应而做出的试探与观察。',
      nodeIds: ['home', 'case_inference', 'case_channel', 'case_handoff', 'ending_case_network', 'ending_case_record', 'ending_case_pause'],
      clues: ['反应试探假说', '独立材料交接'],
      note: '原文中的主人公据遭遇提出这一解释；游戏将它保留为待验证假说，另创反例核对、匿名交接和三种调查收束，不把人物推测当作已揭晓的世界真相。',
    },
  ],
  'double-pursuit': [
    {
      id: 'pursuit-exposed-address',
      label: '威胁已经到达住处',
      quote: '他一连给我发了四条信息，分别是我的姓名、家庭住址、照片、他在我家楼下的照片。',
      nodeIds: ['landing', 'phone', 'evidence_review'],
      clues: ['威胁消息备份', '接警记录'],
      note: '原文写到私人信息暴露、楼下照片及主人公报警；游戏新增消息备份、定位回传和记录核对流程，相关调查结局不代表原作后续。',
    },
    {
      id: 'pursuit-neighbor-shelter',
      label: '熟人的门为何会打开',
      quote: '之所以对隔壁邻居没防备，是因为这个李宇的家伙平时看着非常温和。',
      nodeIds: ['neighbor', 'window', 'kitchen'],
      note: '原文以邻居平日的友好解释主人公为何进入其住处，随后揭示胁迫；游戏改写了周旋与保持距离的选择，未将胁迫认作同意，也未依据行为自行给出医学诊断。',
    },
    {
      id: 'pursuit-photo-wall',
      label: '墙上的偷拍照片',
      quote: '一面墙上挂着的全是我的照片，而且三分之二都是我光着的。',
      nodeIds: ['photographs', 'evidence', 'evidence_check', 'ending_evidence', 'ending_verified'],
      clues: ['室内跟踪证据'],
      note: '原文写明房间内存在侵犯主人公隐私的偷拍照片；游戏新增留存来源、正式交接与调查结局，原文描写本身不等于玩家已取得可提交的证据。',
    },
    {
      id: 'pursuit-police-arrival',
      label: '救援来电要求暂不开门',
      quote: '「我们已经到楼下了，你千万不要开门。」',
      nodeIds: ['stairwell', 'policecheck', 'rescue', 'ending_collective', 'ending_safe'],
      note: '原文有警方来电、到场控制危险及救助受伤住户的情节；游戏新增回拨核验、门牌确认和提前提醒邻居的分支，集体安全与后续安置结果属于改编。',
    },
  ],
  'velvet-alibi': [
    {
      id: 'velvet-mutual-disguise',
      label: '两个人都在隐藏家境',
      quote: '我俩晚上在出租屋相互依偎，白天各自回自己的豪宅假装上班，愣是耗着谁都没说。',
      nodeIds: ['dinner', 'club', 'confession', 'rebuild'],
      clues: ['未说出口的坦白', '共同坦白'],
      note: '原文确立两人共同装穷的前提；游戏新增主动坦白、分别说明财务与意愿、重新建立关系的选择，互相隐瞒并不预定玩家必须继续交往。',
    },
    {
      id: 'velvet-cake-package',
      label: '没换掉的蛋糕盒',
      quote: '我一眼就看出这是个贵牌子，他竟连盒子都不换。',
      nodeIds: ['cake', 'friend'],
      note: '原文以昂贵蛋糕包装暴露男友的伪装；游戏新增通过公开信息核实身份和朋友提供支持的选择，包装的价格不能独自证明完整身世或婚姻安排。',
    },
    {
      id: 'velvet-breakfast-labels',
      label: '换包装的牛奶与面包',
      quote: '我细细品鉴了一下早餐，又跑去厨房翻了翻，发现他把几千块的牛奶灌到瓶子里装廉价牛奶，把国外牌子的面包塞透明塑料袋里当普通面包。',
      nodeIds: ['breakfast', 'evidence_review', 'evidence_check', 'ending_verified'],
      clues: ['换装的早餐'],
      note: '原文提供早餐换包装这一具体细节；游戏新增标签留存与身份、财务、同意分别核对的调查，相关对等约定及结局为原创。',
    },
    {
      id: 'velvet-family-marriage',
      label: '未经本人同意的婚期',
      quote: '爸妈一下黑了脸，全然不顾我的意愿和程家谈起了婚期。',
      nodeIds: ['call', 'invitation', 'family', 'boundary', 'agreement', 'distance', 'ending_equal', 'ending_restart', 'ending_independent'],
      clues: ['明确的拒绝', '共同约定'],
      note: '原文存在父母无视本人意愿安排婚期的冲突；游戏新增明确拒绝、伙伴不代为决定和独立生活等分支，未沿用原文简介中的截婚结果作为必然结局。',
    },
  ],
  'future-island': [
    {
      id: 'island-single-winner-rule',
      label: '只有一个胜者的规则',
      quote: '【请注意，这个游戏只有一个胜者。最后活下来的玩家，才有资格获得奖励。】',
      nodeIds: ['coin', 'control_offer', 'last_decision', 'ending_solitude'],
      clues: ['初始规则原件', '玩家初始名册'],
      note: '原文给出三百名玩家、初始道具和最后存活者获奖的规则；游戏新增留存规则、审视控制提议及不同终局，未声称原文已经废除规则或完成重生。',
    },
    {
      id: 'island-construction-contract',
      label: '建设协议里的工作人员',
      quote: '我宣称自己在做旅游项目，买下了十艘大型邮轮，并与 NPC 签订了建设协议，把工程车和建筑材料全部运送到岛上。',
      nodeIds: ['ledger', 'audit', 'archive', 'evidence_review', 'ending_witness', 'ending_verified'],
      clues: ['施工人员联络册', '未计入的人员档案', '完整证词'],
      note: '原文存在 NPC 参与的建岛工程，并写到末世前工人离岛；游戏新增具名工作人员、联络册、名单审计与证词公开，不把这些新增调查材料当成原文已披露的档案。',
    },
    {
      id: 'island-water-systems',
      label: '岛上的多种水源',
      quote: '水资源也很好解决，我装了雨水收集器/海水淡化系统，并挖到了地下水资源。',
      nodeIds: ['island_plan', 'depot', 'outage', 'logistics_inventory', 'logistics_spare_contact', 'logistics_pump_trial', 'ending_maintenance_pact'],
      clues: ['净水维护配额', '稳定净水配额', '配载机组型号核验', '配载机组试机回单'],
      note: '原文为岛屿设置多种水源和净化设备；游戏新增维护配额、故障、匹配备件、站点试机与维护合作结局，具体数量和供水限制不是原文给出的技术参数。',
    },
    {
      id: 'island-destroyed-transport',
      label: '原作销毁交通工具的分歧点',
      quote: '最后一个星期，我命令集中销毁所有飞机和轮船。',
      nodeIds: ['island_plan', 'dock', 'evac', 'logistics_intake', 'logistics_table', 'logistics_cargo', 'logistics_manifest', 'logistics_crossing', 'logistics_receipts', 'logistics_return', 'ending_ark', 'ending_maintenance_pact'],
      clues: ['船坞转运配额', '联合航线', '配载出航确认', '配载返航核销'],
      note: '原文写明集中销毁所有飞机和轮船；保留受限工作艇是游戏明确采用的改编分歧，四格配载、核验航次、签收试机与维护合作结局均为原创，不能据此当作原作已有的救援路线。',
    },
    {
      id: 'island-flood-disaster',
      label: '先到来的灾难是洪水',
      quote: '从北到南，长时间、高强度的大雨引发了大洪水，就像神话中的史前大洪水一样凶猛。',
      nodeIds: ['storm', 'triage', 'stranger_signal', 'relay', 'council', 'vault', 'redistribution', 'ending_commons'],
      clues: ['需求核对标准', '双端通信时间线', '公开配给公约'],
      note: '原文以持续暴雨、洪水和其他玩家物资不足展开末世；游戏新增灾后通信、需求核对、公开配给与独立封存选择，合作救助和相关结局不属于现有节选内容。',
    },
  ],
};
