#!/usr/bin/env python3
"""Build immutable WebP delivery copies of the reviewed RedRain artwork.

The production PNGs are read only. Generated files do not become visible in the
game until the caller publishes the generated JavaScript asset map.
"""

from __future__ import annotations

import argparse
from concurrent.futures import ProcessPoolExecutor, as_completed
from datetime import datetime, timezone
from hashlib import sha256
from io import BytesIO
import json
import os
from pathlib import Path
import re

from PIL import Image, features


PROJECT_ROOT = Path(__file__).resolve().parent.parent
ASSET_LITERAL = re.compile(r'''["'](\./public/assets/[^"']+\.(?:png|jpe?g|webp))["']''')


def atomic_write(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{os.getpid()}.tmp")
    try:
        temporary.write_bytes(data)
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def reviewed_sources(game_dir: Path) -> list[str]:
    sources: set[str] = set()
    for name in ("retro-assets.js", "bad-end-art.js"):
        module = game_dir / "src" / name
        sources.update(ASSET_LITERAL.findall(module.read_text(encoding="utf-8")))
    if not sources:
        raise ValueError("No reviewed artwork was found in the asset modules")
    return sorted(sources)


def optimize_one(game_directory: str, source_url: str, quality: int, method: int) -> dict:
    game_dir = Path(game_directory)
    source = (game_dir / source_url.removeprefix("./")).resolve()
    asset_root = (game_dir / "public" / "assets").resolve()
    if not source.is_relative_to(asset_root):
        raise ValueError(f"Asset is outside the game asset directory: {source_url}")
    original = source.read_bytes()
    source_digest = sha256(original).hexdigest()
    with Image.open(BytesIO(original)) as image:
        if image.mode not in ("RGB", "RGBA"):
            image = image.convert("RGBA" if "transparency" in image.info else "RGB")
        original_size = image.size
        source_mode = image.mode
        original_alpha = image.getchannel("A").tobytes() if "A" in image.getbands() else None
        buffer = BytesIO()
        options = {"quality": quality, "method": method, "exact": True}
        if image.info.get("icc_profile"):
            options["icc_profile"] = image.info["icc_profile"]
        image.save(buffer, "WEBP", **options)
        encoded = buffer.getvalue()

    with Image.open(BytesIO(encoded)) as check:
        check.load()
        if check.size != original_size:
            raise ValueError(f"Image dimensions changed: {source_url}")
        if original_alpha is not None and check.convert("RGBA").getchannel("A").tobytes() != original_alpha:
            raise ValueError(f"Transparency changed: {source_url}")
        optimized_mode = check.mode

    digest = sha256(encoded).hexdigest()
    output_name = f"{source.stem}.{digest[:16]}.webp"
    output_path = asset_root / "optimized" / output_name
    if output_path.exists():
        if output_path.read_bytes() != encoded:
            raise ValueError(f"Content hash collision: {output_name}")
    else:
        atomic_write(output_path, encoded)
    if sha256(source.read_bytes()).hexdigest() != source_digest:
        raise ValueError(f"Original image changed during optimization: {source_url}")

    return {
        "source": source_url,
        "optimized": f"./public/assets/optimized/{output_name}",
        "sourceSha256": source_digest,
        "optimizedSha256": digest,
        "originalBytes": len(original),
        "optimizedBytes": len(encoded),
        "savingsPercent": round((1 - len(encoded) / len(original)) * 100, 2),
        "width": original_size[0],
        "height": original_size[1],
        "sourceMode": source_mode,
        "optimizedMode": optimized_mode,
        "dimensionsVerified": True,
        "alphaVerified": original_alpha is not None,
        "originalUnchanged": True,
    }


def module_source(files: list[dict]) -> str:
    mapping = {item["source"]: item["optimized"] for item in files}
    return (
        "// Generated by scripts/optimize-redrain-assets.py; original PNGs remain available.\n"
        "export const OPTIMIZED_ASSETS = Object.freeze("
        + json.dumps(mapping, ensure_ascii=False, indent=2)
        + ");\n\n"
        "export function optimizedAsset(source) {\n"
        "  return OPTIMIZED_ASSETS[source] || source;\n"
        "}\n\n"
        "export function assetCandidates(sources) {\n"
        "  const originals = Array.isArray(sources) ? sources : [sources];\n"
        "  return [...new Set(originals.filter(Boolean).flatMap(source => [optimizedAsset(source), source]))];\n"
        "}\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--game-dir", type=Path, default=PROJECT_ROOT / "public/games/redrain")
    parser.add_argument("--module-output", type=Path, default=PROJECT_ROOT / "output/redrain-art-speed/staging/src/optimized-assets.js")
    parser.add_argument("--report-output", type=Path, default=PROJECT_ROOT / "output/redrain-art-speed/assets-report.json")
    parser.add_argument("--quality", type=int, default=86, choices=range(1, 101), metavar="1..100")
    parser.add_argument("--method", type=int, default=6, choices=range(7), metavar="0..6")
    parser.add_argument("--workers", type=int, default=min(3, os.cpu_count() or 1))
    args = parser.parse_args()
    if args.workers < 1:
        parser.error("--workers must be at least 1")
    if not features.check("webp"):
        parser.error("Pillow was built without WebP support")

    game_dir = args.game_dir.resolve()
    sources = reviewed_sources(game_dir)
    files: list[dict] = []
    print(json.dumps({"reviewedAssets": len(sources), "quality": args.quality, "method": args.method, "workers": args.workers}), flush=True)
    with ProcessPoolExecutor(max_workers=args.workers) as pool:
        tasks = {pool.submit(optimize_one, str(game_dir), source, args.quality, args.method): source for source in sources}
        for task in as_completed(tasks):
            files.append(task.result())
            if len(files) <= 5 or len(files) % 10 == 0 or len(files) == len(sources):
                original_bytes = sum(item["originalBytes"] for item in files)
                optimized_bytes = sum(item["optimizedBytes"] for item in files)
                print(json.dumps({"completed": len(files), "total": len(sources), "originalBytes": original_bytes, "optimizedBytes": optimized_bytes, "savingsPercent": round((1 - optimized_bytes / original_bytes) * 100, 2)}), flush=True)

    files.sort(key=lambda item: item["source"])
    original_bytes = sum(item["originalBytes"] for item in files)
    optimized_bytes = sum(item["optimizedBytes"] for item in files)
    report = {
        "generatedAt": datetime.now(timezone.utc).isoformat(),
        "gameDirectory": str(game_dir),
        "quality": args.quality,
        "method": args.method,
        "assets": len(files),
        "originalBytes": original_bytes,
        "optimizedBytes": optimized_bytes,
        "savedBytes": original_bytes - optimized_bytes,
        "savingsPercent": round((1 - optimized_bytes / original_bytes) * 100, 2),
        "dimensionsVerified": all(item["dimensionsVerified"] for item in files),
        "alphaAssetsVerified": sum(item["alphaVerified"] for item in files),
        "originalsUnchanged": all(item["originalUnchanged"] for item in files),
        "files": files,
    }
    atomic_write(args.report_output, (json.dumps(report, ensure_ascii=False, indent=2) + "\n").encode("utf-8"))
    atomic_write(args.module_output, module_source(files).encode("utf-8"))
    print(json.dumps({key: value for key, value in report.items() if key != "files"}), flush=True)


if __name__ == "__main__":
    main()
